# Required
version: 2

#Set the OS, Python version and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:

    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
    pre_install:
    #idea is to use poetry to build the package, and then export it to a
    #requirements file with all the groups.

    # Then (see python block), the environment is build by a pip install the
    # requirements file.

    #all the groups are needed because figures are genereted, making use of
    #the package itself! Thus no mocks in the
      - pwd
      - ls
      - poetry install --all-extras
      # create a requirements file of the poetry env
      #- rm -f ./docs/rtd_requirements.txt
      #Specify all the groups (do not use --all-extras because that does not work???)
      - poetry show
      - poetry build
      - poetry export --without-hashes --with=dev,documentation --format=requirements.txt --output=dist/rtd_requirements.txt
    pre_build:
    # Just print out the environment the documentation is build in
      - python -m pip list
      - pip install -r dist/rtd_requirements.txt #install all extra requirements
      # - pip install dist/metobs_toolkit-*.whl #install the package (needed for examples)
      - pip list

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: ./dist/rtd_requirements.txt
   - method: pip
     path: dist/metobs_toolkit-*.whl
