# Required
version: 2

#Set the OS, Python version and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:

    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # - apt-get -y install pandoc
   # post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      #- VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with documentation
    pre_install:
      - pwd
      - ls
      - poetry build
    pre_build:
      - python -m pip list
      #create a python environment
     # - poetry install --all-extras
      # create a requirements file of the poetry env
      #- rm -f ./docs/rtd_requirements.txt
     # - poetry export --without-hashes --with=documentation --format=requirements.txt > ./docs/rtd_requirements.txt
      #run test?
      #- poetry run python rtdtest.py
      #build doc in sphinx env (this is not pre build !!)
      #- poetry run sphinx-build -a -E -v ./docs/ ./docs/_build/




# Build documentation in the "docs/" directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - requirements: ./docs/rtd_requirements.txt
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - documentation
        - titan
        - dev
