[pytest]
testpaths =
    tests
    docs/examples
    docs/topics
addopts = -v --tb=short --nbval-lax --mpl --mpl-generate-summary=html
mpl-baseline-path = tests/baseline
markers =
    demo: mark test as a demo test
    --mpl: enable matplotlib image comparison tests
