#!/usr/bin/env bash

#clear builds

rm -r _build/*
rm -r _autosummary/*

cd reference/api
rm *.rst
cd ../..

cd ..

sphinx-build -a -E -v docs/ docs/_build/
#sphinx-build -v docs/ docs/_build/
cd docs
