#!/usr/bin/env bash

#This file must be sourced from within docs/ !!!

#clear builds
rm -rf _build
rm -rf _autosummary

# Create _build directory if it does not exist
mkdir -p _build

cd reference/api
rm -rf *.rst
cd ../..

cd ..

sphinx-build -a -E -v docs/ docs/_build/
#sphinx-build -v docs/ docs/_build/
cd docs
