name: Code style format with Black
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: "./metobs_toolkit --verbose"