name: Run Pytest framework

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ipython
          pip install -e .
          pip install pytest
          pip install pytest-mpl

      # List installed packages
      - name: List installed packages
        run: |
          pip list

      # Run tests
      - name: Run Pytest
        run: |
          # Run all tests except the gee test (auth tokens required, only local testing)
          #pytest toolkit_tests --mpl --ignore=toolkit_tests/test_gee.py
          pytest toolkit_tests/test_obstypes.py
