name: Run Pytest framework

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    # Dynamically create a matrix of test files
    strategy:
      matrix:
        test_file:
          - toolkit_tests/test_qc.py
          - toolkit_tests/test_obstypes.py
          - toolkit_tests/test_gf.py

        # Exclude the test_gee.py file
        exclude:
          - test_file: toolkit_tests/test_gee.py #requires GEE credentials

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies (only once, cached)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ipython
          pip install -e .
          pip install pytest
          pip install pytest-mpl

      # List installed packages
      - name: List installed packages
        run: |
          pip list

      # Run tests for the specific test file
      - name: Run Pytest
        run: |
          pytest ${{ matrix.test_file }} --mpl
