name: TRIGGERING

on:
  push:

jobs:
    get-pr:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        output1: ${{ steps.trigger.outputs.triggered_by_label }}
      steps:
        - uses: 8BitJonny/gh-get-current-pr@3.0.0
          id: PR
          with:
            # Authetication token to access GitHub APIs. (Can be omitted by default.)
            github-token: ${{ github.token }}
            # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
            sha: ${{ github.sha }}
        - run: echo "triggered_by_label=false" >> $GITHUB_ENV #init,can be overwritten

        - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prLabel}"
          if: steps.PR.outputs.pr_found == 'true'
          env:
              # JSON object with the full PR object
              # toJSON(fromJSON(...pr)) parses it into memory and then format is with pretty-print.
              prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
              # Direct access to common PR properties
              prNumber: ${{ steps.PR.outputs.number }}
              prUrl: ${{ steps.PR.outputs.pr_url }}
              prTitle: ${{ steps.PR.outputs.pr_title }}
              prBody: ${{ steps.PR.outputs.pr_body }}
              prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
              prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
              prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
              prLabel: ${{ steps.PR.outputs.pr_labels }}

        - name: set_trigger_label
          id: trigger
          run: |
            if [[ "$prLabel" == *"RUN TESTS"* ]]; then
                echo "The label 'RUN TESTS' is present."
                echo "triggered_by_label=true" >> $GITHUB_ENV
            else
                echo "The label 'RUN TESTS' is not present."
                echo "triggered_by_label=false" >> $GITHUB_ENV
            fi
          env:
              prLabel: ${{ steps.PR.outputs.pr_labels }}




    next-job:
    #   if:
    #     github.ref == 'refs/heads/main' ||
    #     github.ref == 'refs/heads/develop' ||
    #     needs.get-pr.outputs.output1 == 'true'
      env:
        FLAG: ${{ needs.get-pr.outputs.output1 }}
      runs-on: ubuntu-latest
      needs: get-pr
      steps:
        - name: debug
          run: |
            echo "This is running !!! "
            echo "triggered_by_label=${{ needs.get-pr.outputs.output1 }}"
            echo "FLAG=${{ env.FLAG }}"
            echo "FLAG=$FLAG"
        - name: yess
          run: |
                echo "This is running !!! "
