name: TRIGGERING

on:
  push:

jobs:
    scan-pr-labels:
        runs-on: ubuntu-latest
        # Map a step output to a job output
        outputs:
            output1: ${{ steps.ispresent.outputs.labelispresent }}
        steps:
        - uses: 8BitJonny/gh-get-current-pr@3.0.0
          id: PR
          with:
            # Authetication token to access GitHub APIs. (Can be omitted by default.)
            github-token: ${{ github.token }}
            # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
            sha: ${{ github.sha }}

        - id: ispresent
          env:
            prLabel: ${{ steps.PR.outputs.pr_labels }}
          run: |
              if [[ "$prLabel" == *"RUN TESTS"* ]]; then
                  echo "The label 'RUN TESTS' is present."
                  echo "labelispresent=1" >> "$GITHUB_OUTPUT"
              else
                  echo "The label 'RUN TESTS' is not present."
                  echo "labelispresent=0" >> "$GITHUB_OUTPUT"
              fi

    launch-pipeline:
        runs-on: ubuntu-latest
        needs: scan-pr-labels
        if :
            github.ref == 'refs/heads/main' ||
            github.ref == 'refs/heads/develop' ||
            github.event_name == 'pull_request' ||
            github.event_name == 'workflow_dispatch' ||
            needs.scan-pr-labels.outputs.output1 == '1'
        env:
          OUTPUT1: ${{ needs.scan-pr-labels.outputs.output1 }}

        steps:
          - env:
              OUTPUT1: ${{needs.job1.outputs.output1}}
            run: echo "$OUTPUT1"
